version: '3.4'

services:
  zookeeper:
    image: bitnami/zookeeper
    restart: always
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka
    ports:
      - 9092:9092
    restart: always
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
  mongodb:
    image: mongo:latest
    container_name: mongo-container
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: sql-container
    restart: always
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=Str0ngS@P@ssw0rd02"
      - "MSSQL_PID=Express"
    ports:
      - 1433:1433

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongodb_data_container:
    driver: local

networks:
  default:
    name: mydockernetwork
